"""AC3 — content parity over the generated corpus.

Two gates, both over the same self-generated `.msg` corpus:

  1. **Authored ground truth** (always on, portable): the port's extraction
     equals what the fixture was authored to contain — the strong gate, since
     the corpus author knows exactly what each fixture holds.
  2. **Independent cross-check oracle** (durable): the port equals a committed
     baseline captured from the mature Node `msgreader` package reading the same
     bytes (`testdata/msgreader_baseline.json`). A different codebase agreeing on
     subject / recipient-emails / attachment-names catches a port blind spot on
     the generated bytes.

Neither closes the real-world blind spot (both readers only ever see bytes the
CFBF writer chose to emit); that absolute-fidelity signal is genuinely deferred
(backlog: extraction-msg-realworld-sample).

Run with `python -m pytest` from this directory.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

import mapi
import msg_fixtures as fx

HERE = Path(__file__).resolve().parent
BASELINE = json.loads((HERE / "testdata" / "msgreader_baseline.json").read_text())

CORPUS = fx.corpus()


@pytest.mark.parametrize("name,spec,truth", CORPUS, ids=[c[0] for c in CORPUS])
def test_port_matches_authored_ground_truth(tmp_path, name, spec, truth):
    p = fx.write_msg(str(tmp_path / "f.msg"), spec)
    m = mapi.read_msg(p)
    assert m.subject == truth["subject"]
    assert m.sender_email == truth["sender_email"]
    assert {r.email for r in m.recipients} == truth["recipient_emails"]
    # Kind (incl. bcc) is classified from raw RecipientType and checked vs authored
    # truth — the Node oracle surfaces addresses but not kind, so it cannot verify this.
    assert {r.kind for r in m.recipients} == truth["kinds"]
    assert m.body_kind == truth["body_kind"]
    assert {a.filename for a in m.attachments} == truth["attachment_names"]
    assert sum(1 for a in m.attachments if a.is_embedded_msg) == truth["embedded"]
    if "importance" in truth:
        assert m.importance == truth["importance"]


@pytest.mark.parametrize("name,spec,truth", CORPUS, ids=[c[0] for c in CORPUS])
def test_port_matches_independent_msgreader_oracle(tmp_path, name, spec, truth):
    safe = name.replace(" ", "_")
    if safe not in BASELINE:
        pytest.skip(f"no committed oracle baseline for {safe}")
    base = BASELINE[safe]
    p = fx.write_msg(str(tmp_path / "f.msg"), spec)
    m = mapi.read_msg(p)
    assert (m.subject or None) == base["subject"]
    assert sorted(r.email for r in m.recipients if r.email) == base["recipientEmails"]
    assert sorted(a.filename for a in m.attachments) == base["attachmentNames"]
