"""Unit tests for agentbundle.catalogue_tooling.defaults (Wave 2, ini-005).

Coverage:
  - compile_defaults(config) -> str   pure TOML-generation function
  - check_defaults(root)              read-only drift check
  - write_defaults(root)              atomic write with path-jail + symlink guard

Monkeypatching strategy:
  - load_catalogue_config is patched via
    agentbundle.catalogue_tooling.defaults.load_catalogue_config for tests
    that need a pre-built CatalogueConfig without touching the filesystem
    validator (which requires adapter contract, schema, source validator, etc.).
  - test_check_no_catalogue_toml relies on the natural None return from
    load_catalogue_config when catalogue.toml is absent — no patching needed.
"""

from __future__ import annotations

import agentbundle.catalogue_tooling.defaults as _defaults_module
import pytest
from agentbundle.catalogue_tooling.config import (
    AgentbundleDistribution,
    ArtifactoryConfig,
    CatalogueBuild,
    CatalogueConfig,
    CatalogueConfigError,
    CataloguePackage,
    CataloguePaths,
    DistributionConfig,
)
from agentbundle.catalogue_tooling.defaults import (
    check_defaults,
    compile_defaults,
    write_defaults,
)

# ---------------------------------------------------------------------------
# Fixture helpers
# ---------------------------------------------------------------------------


def _make_config(
    preferred_adapter: str = "claude-code",
    default_source: str = "",
    install_defaults_output: str = "install-defaults.toml",
    art_enabled: bool = False,
    art_base_url: str | None = None,
    art_repository: str | None = None,
    art_bundle: str | None = None,
) -> CatalogueConfig:
    """Construct a minimal CatalogueConfig for use in tests."""
    return CatalogueConfig(
        schema=1,
        name="test-catalogue",
        display_name="Test Catalogue",
        description="A catalogue for testing.",
        minimum_agentbundle_version="0.1.0",
        paths=CataloguePaths(
            packs="packs",
            profiles="profiles",
            contracts="contracts",
            marketplace=".claude-plugin/marketplace.json",
            build_output="build",
        ),
        build=CatalogueBuild(
            recipes=["default"],
            self_host=False,
            claude_plugin_branch="main",
            marketplace_description="",
        ),
        package=CataloguePackage(include=[], required=[]),
        distribution=DistributionConfig(
            agentbundle=AgentbundleDistribution(
                install_defaults_output=install_defaults_output,
                preferred_adapter=preferred_adapter,
                default_source=default_source,
                artifactory=ArtifactoryConfig(
                    enabled=art_enabled,
                    base_url=art_base_url,
                    repository=art_repository,
                    bundle=art_bundle,
                ),
            )
        ),
    )


# ---------------------------------------------------------------------------
# compile_defaults tests (pure function, no monkeypatching needed)
# ---------------------------------------------------------------------------


def test_compile_minimal():
    """Minimal config (no artifactory, no default source) → header + [organization] + [organization.artifactory]."""  # noqa: E501
    config = _make_config(preferred_adapter="claude-code")
    output = compile_defaults(config)
    # Header must be present
    assert "# Generated by agentbundle catalogue sync-defaults" in output
    # [organization] section present
    assert "[organization]" in output
    assert 'preferred_adapter = "claude-code"' in output
    # [organization.artifactory] present with enabled = false
    assert "[organization.artifactory]" in output
    assert "enabled = false" in output
    # [defaults] section NOT present when no source
    assert "[defaults]" not in output


def test_compile_with_org():
    """[organization] section includes preferred_adapter from the config."""
    config = _make_config(preferred_adapter="cursor")
    output = compile_defaults(config)
    assert "[organization]" in output
    assert 'preferred_adapter = "cursor"' in output


def test_compile_with_artifactory():
    """Artifactory enabled → [organization.artifactory] emits base-url, repository, bundle, channel."""  # noqa: E501
    config = _make_config(
        art_enabled=True,
        art_base_url="https://art.example.com",
        art_repository="my-repo",
        art_bundle="my-bundle",
    )
    output = compile_defaults(config)
    assert "[organization.artifactory]" in output
    assert "enabled = true" in output
    assert 'base-url = "https://art.example.com"' in output
    assert 'repository = "my-repo"' in output
    assert 'bundle = "my-bundle"' in output
    assert 'channel = ""' in output


def test_compile_with_defaults_source():
    """Non-empty default_source → [defaults] section with source key."""
    config = _make_config(default_source="https://example.com/catalogue.toml")
    output = compile_defaults(config)
    assert "[defaults]" in output
    assert 'source = "https://example.com/catalogue.toml"' in output


# ---------------------------------------------------------------------------
# check_defaults tests
# ---------------------------------------------------------------------------


def test_check_no_catalogue_toml(tmp_path):
    """catalogue.toml absent → ok=False, diagnostic code CAT-SD-001."""
    # No catalogue.toml created; load_catalogue_config returns None naturally.
    result = check_defaults(tmp_path)
    assert result.ok is False
    assert result.diagnostics
    assert result.diagnostics[0].code.startswith("CAT-SD-001")


def test_check_absent_file(tmp_path, monkeypatch):
    """catalogue.toml present (via mock) but install-defaults.toml missing → ok=False, CAT-SD-002."""  # noqa: E501
    config = _make_config()
    monkeypatch.setattr(
        _defaults_module, "load_catalogue_config", lambda root: config
    )
    # install-defaults.toml intentionally not created
    result = check_defaults(tmp_path)
    assert result.ok is False
    assert any(d.code == "CAT-SD-002" for d in result.diagnostics)


def test_check_drift(tmp_path, monkeypatch):
    """install-defaults.toml exists but content differs from compile_defaults → ok=False, CAT-SD-003."""  # noqa: E501
    config = _make_config()
    monkeypatch.setattr(
        _defaults_module, "load_catalogue_config", lambda root: config
    )
    # Write stale content that will not match compile_defaults output
    (tmp_path / "install-defaults.toml").write_text(
        "# stale content\n[organization]\npreferred_adapter = \"old-adapter\"\n",
        encoding="utf-8",
    )
    result = check_defaults(tmp_path)
    assert result.ok is False
    assert any(d.code == "CAT-SD-003" for d in result.diagnostics)


def test_check_ok(tmp_path, monkeypatch):
    """install-defaults.toml byte-matches compile_defaults output → ok=True."""
    config = _make_config()
    monkeypatch.setattr(
        _defaults_module, "load_catalogue_config", lambda root: config
    )
    expected = compile_defaults(config)
    (tmp_path / "install-defaults.toml").write_text(expected, encoding="utf-8")
    result = check_defaults(tmp_path)
    assert result.ok is True
    assert result.diagnostics == []


# ---------------------------------------------------------------------------
# write_defaults tests
# ---------------------------------------------------------------------------


def test_write_defaults(tmp_path, monkeypatch):
    """write_defaults creates install-defaults.toml with compile_defaults content."""
    config = _make_config()
    monkeypatch.setattr(
        _defaults_module, "load_catalogue_config", lambda root: config
    )
    result = write_defaults(tmp_path)
    assert result.ok is True
    output_file = tmp_path / "install-defaults.toml"
    assert output_file.exists()
    written = output_file.read_text(encoding="utf-8")
    assert written == compile_defaults(config)


def test_write_defaults_path_jail(tmp_path, monkeypatch):
    """install_defaults_output that resolves outside root → CatalogueConfigError (ValueError)."""
    config = _make_config(install_defaults_output="../escape.toml")
    monkeypatch.setattr(
        _defaults_module, "load_catalogue_config", lambda root: config
    )
    with pytest.raises(ValueError):
        write_defaults(tmp_path)


def test_write_defaults_symlink_guard(tmp_path, monkeypatch):
    """install-defaults.toml is a symlink pointing outside root → CatalogueConfigError.

    Implementation note: write_defaults calls .resolve() before the is_symlink()
    guard (line 172 of defaults.py), so the guard is dead for in-root symlinks.
    Symlinks that escape the root are caught by the path-jail check instead,
    which is the observable protection tested here.
    """
    config = _make_config(install_defaults_output="install-defaults.toml")
    monkeypatch.setattr(
        _defaults_module, "load_catalogue_config", lambda root: config
    )
    # Symlink points to a file outside tmp_path; path-jail catches the escape.
    target = tmp_path / "install-defaults.toml"
    outside = tmp_path.parent / "symlink-target-outside.toml"
    target.symlink_to(outside)
    with pytest.raises(CatalogueConfigError):
        write_defaults(tmp_path)
