"""Catalogue sync-defaults: compile, check, and write install-defaults.toml.

Spec: docs/specs/catalogue-tooling-sync-defaults/spec.md (ini-005 Bucket 4).

The generated install-defaults.toml is the single source of truth for
adapter preference, Artifactory bootstrap coordinates, and default source.
No credentials are written; auth stays in environment variables.
"""

from __future__ import annotations

from pathlib import Path

from agentbundle.catalogue_tooling.config import (
    CatalogueConfig,
    CatalogueConfigError,
    load_catalogue_config,
)
from agentbundle.catalogue_tooling.results import Diagnostic, Severity, SyncDefaultsResult

_GENERATED_HEADER = (
    "# Generated by agentbundle catalogue sync-defaults"
    " — source of truth: catalogue.toml\n"
)

_AGENTBUNDLE_VERSION: str | None = None


def _get_agentbundle_version() -> str:
    global _AGENTBUNDLE_VERSION
    if _AGENTBUNDLE_VERSION is None:
        try:
            from agentbundle import __version__
            _AGENTBUNDLE_VERSION = __version__
        except Exception:
            _AGENTBUNDLE_VERSION = "unknown"
    return _AGENTBUNDLE_VERSION


def _emit_str(value: str) -> str:
    """Emit a TOML basic-string literal (double-quoted, minimal escaping)."""
    escaped = (
        value
        .replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def _emit_bool(value: bool) -> str:
    return "true" if value else "false"


def _emit_section(header: str, rows: list[tuple[str, str]]) -> str:
    """Emit one TOML section as [header]\\nkey = value\\n..."""
    lines = [f"[{header}]"]
    for key, val in rows:
        lines.append(f"{key} = {val}")
    return "\n".join(lines) + "\n"


def compile_defaults(config: CatalogueConfig) -> str:
    """Pure function. Deterministic TOML string from CatalogueConfig.

    Sections in order: [organization], [organization.artifactory], [defaults].
    No credentials emitted regardless of config content.
    """
    parts: list[str] = [_GENERATED_HEADER]

    # [organization]
    parts.append(_emit_section(
        "organization",
        [("preferred_adapter", _emit_str(config.distribution.agentbundle.preferred_adapter))],
    ))
    parts.append("\n")

    # [organization.artifactory]
    art = config.distribution.agentbundle.artifactory
    art_rows: list[tuple[str, str]] = [("enabled", _emit_bool(art.enabled))]
    if art.enabled:
        art_rows.append(("base-url", _emit_str(art.base_url or "")))
        art_rows.append(("repository", _emit_str(art.repository or "")))
        art_rows.append(("bundle", _emit_str(art.bundle or "")))
        # channel is not in ArtifactoryConfig dataclass — emit empty when enabled
        art_rows.append(("channel", _emit_str("")))
    parts.append(_emit_section("organization.artifactory", art_rows))

    # [defaults]
    source = config.distribution.agentbundle.default_source
    defaults_rows: list[tuple[str, str]] = []
    if source:
        defaults_rows.append(("source", _emit_str(source)))
    if defaults_rows:
        parts.append("\n")
        parts.append(_emit_section("defaults", defaults_rows))

    # [pack-defaults.<pack>] — sorted by pack name, then by key within each section.
    for pack_name in sorted(config.pack_defaults):
        kv = config.pack_defaults[pack_name]
        rows: list[tuple[str, str]] = sorted(
            (k, _emit_str(v)) for k, v in kv.items()
        )
        if rows:
            parts.append("\n")
            parts.append(_emit_section(f"pack-defaults.{pack_name}", rows))

    return "".join(parts)


def _make_result(
    ok: bool,
    operation: str,
    diagnostics: list[Diagnostic] | None = None,
    schema_ver: int = 1,
) -> SyncDefaultsResult:
    return SyncDefaultsResult(
        ok=ok,
        diagnostics=diagnostics or [],
        schema_version=schema_ver,
        command="catalogue sync-defaults",
        operation=operation,
        agentbundle_version=_get_agentbundle_version(),
        catalogue_schema_version=1,
    )


def check_defaults(root: Path) -> SyncDefaultsResult:
    """Read-only drift check. ok=True iff current file byte-matches compile_defaults output."""
    config = load_catalogue_config(root)
    if config is None:
        diag = Diagnostic(
            code="CAT-SD-001",
            severity=Severity.ERROR,
            pack=None,
            path=str(root / "catalogue.toml"),
            line=None,
            col=None,
            message="catalogue.toml is absent; sync-defaults requires it",
            remediation="Add a catalogue.toml at the catalogue root.",
        )
        return _make_result(False, "check", [diag])

    expected = compile_defaults(config)
    output_path = root / config.distribution.agentbundle.install_defaults_output
    if not output_path.exists():
        diag = Diagnostic(
            code="CAT-SD-002",
            severity=Severity.ERROR,
            pack=None,
            path=str(output_path),
            line=None,
            col=None,
            message="install-defaults.toml is absent",
            remediation="Run 'agentbundle catalogue sync-defaults --write' to generate it.",
        )
        return _make_result(False, "check", [diag])

    current = output_path.read_text(encoding="utf-8")
    if current != expected:
        diag = Diagnostic(
            code="CAT-SD-003",
            severity=Severity.ERROR,
            pack=None,
            path=str(output_path),
            line=None,
            col=None,
            message="install-defaults.toml has drifted from catalogue.toml",
            remediation="Run 'agentbundle catalogue sync-defaults --write' to regenerate.",
        )
        return _make_result(False, "check", [diag])

    return _make_result(True, "check")


def write_defaults(root: Path) -> SyncDefaultsResult:
    """Atomic write of install-defaults.toml. Enforces path jail + symlink guard."""
    config = load_catalogue_config(root)
    if config is None:
        raise CatalogueConfigError(
            "write_defaults: catalogue.toml is absent; cannot generate install-defaults.toml"
        )

    # Symlink guard must run on the raw (unresolved) path before .resolve()
    # follows the link — once resolved the symlink disappears.
    output_raw = root / config.distribution.agentbundle.install_defaults_output
    if output_raw.is_symlink():
        raise CatalogueConfigError(
            f"write_defaults: output path {output_raw} is a symlink; refusing to overwrite"
        )

    output_path = output_raw.resolve()

    # Path jail: output must be inside root
    root_resolved = root.resolve()
    if not output_path.is_relative_to(root_resolved):
        raise CatalogueConfigError(
            f"write_defaults: output path {output_path} escapes catalogue root {root_resolved}"
        )

    content = compile_defaults(config)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    tmp = output_path.with_suffix(".tmp")
    try:
        tmp.write_text(content, encoding="utf-8", newline="\n")
        tmp.rename(output_path)
    except Exception:
        tmp.unlink(missing_ok=True)
        raise

    return _make_result(True, "write")
