"""The aggregated marketplace entry agrees with the pack it is generated from.

`.claude-plugin/marketplace.json` is regenerated by `make build-self` from every
pack's `.claude-plugin/plugin.json`, so a stale aggregate means the regeneration
was skipped or its output was hand-edited. Either way a consumer resolving the
pack from the marketplace gets a version the pack does not carry.

This lives in `tests/roster/` rather than beside the pack because it compares a
repository-level artifact with a pack-level one, and a pack test may not read
above its own pack -- `tools/lint-pack-test-boundary.py` enforces that, and it
is the check that moved this assertion here. The pack-local half of the release
surface stays at `packs/atlassian/tests/pack/test_release_surface.py`.
"""

from __future__ import annotations

import json
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
MARKETPLACE_JSON = REPO_ROOT / ".claude-plugin" / "marketplace.json"
PACK_NAME = "atlassian"
PACK_TOML = REPO_ROOT / "packs" / PACK_NAME / "pack.toml"


def _pack_version() -> str:
    with PACK_TOML.open("rb") as handle:
        return tomllib.load(handle)["pack"]["version"]


def test_the_marketplace_aggregate_carries_the_pack_version() -> None:
    marketplace = json.loads(MARKETPLACE_JSON.read_text(encoding="utf-8"))
    entries = [p for p in marketplace["plugins"] if p.get("name") == PACK_NAME]

    assert len(entries) == 1, f"expected one {PACK_NAME} entry, found {len(entries)}"
    assert entries[0]["version"] == _pack_version(), (
        f"marketplace.json carries {entries[0]['version']!r} for {PACK_NAME} but "
        f"pack.toml carries {_pack_version()!r} -- run `make build-self`"
    )
