#!/usr/bin/env python3
"""Probe: what each scoping flag's subtree resolves to, and whether narrowing
the replay's own selection is a safe way to implement a scoped run.

Run from the repository root:
    python3 docs/specs/catalogue-sync-apply/notes/grounding/probe-scope-subtrees.py
"""
from __future__ import annotations

import inspect
import sys
from pathlib import Path

sys.path.insert(0, str(Path.cwd() / "packages" / "agentbundle"))

from agentbundle.build.user_libs import PACK_NAME, PACKAGE_SUBPATH  # noqa: E402
from agentbundle.catalogue_tooling import initialise_self_hosted as ish  # noqa: E402

print("1. --package subtree destinations, as replay_derivation writes them")
print(f"   credbroker  -> {PACKAGE_SUBPATH.parent.as_posix()}/   "
      f"(gated on pack {PACK_NAME!r} being selected)")
print(f"   agentbundle -> {ish._VENDORED_TOOLING_ROOT}/agentbundle/   "
      f"(gated on tooling == 'vendored')")
print(f"   state file  -> {ish._OWNERSHIP_STATE_FILE}")

print("\n2. Does cfg.packs narrow the replay's own planned set?")
src = inspect.getsource(ish.collect_fields)
line = next(row.strip() for row in src.splitlines() if "cfg.packs if" in row)
print(f"   collect_fields: {line}")
print("   -> a non-None cfg.packs REPLACES the recorded recipe selection,")
print("      so file_bytes would carry only the named packs.")

print("\n3. What consumes the full planned set?")
sig = inspect.signature(ish._plan_stale_owned_paths)
print(f"   _plan_stale_owned_paths{sig}")
print("   -> `current_paths` is the keep-set: every recorded path NOT in it is")
print("      a removal candidate. Passing a scoped subset here would make every")
print("      out-of-scope recorded path stale.")

print("\n4. Derivation-wide paths § Granularity says move only with a full sync")
print("   catalogue.toml            (always generated by the replay)")
print("   tests/conformance/        (always collected when present in source)")
print("   identity fields           (recipe name/display_name/owner/... )")
